function mainMenu() {
	return "<div id='cssmenu'>"
			+"<ul class=l0>"
			+"   <li id='mainmenu-home'><a href='index.html'><span>Home</span></a></li>"
			+"   <li id='mainmenu-about' class='has-sub '><a href='about.html'><span>About</span></a>"
			+"      <ul class=l1>"
			+"         <li><a href='about.html'><span>About Us</span></a></li>"
			+"         <li><a href='about.html?option=pastor'><span>Our Pastor</span></a></li>"
			+"         <li><a href='about.html?option=facility'><span>Our Facility</span></a></li>"
			+"         <li><a href='about.html?option=mennonites'><span>Who are the Mennonites?</span></a></li>"
			+"         <li><a href='about.html?option=confession'><span>Confession of Faith</span></a></li>"
			+"         <li><a href='findus.html'><span>Directions</span></a></li>"
			+"      </ul>"
			+"   </li>"
			+"   <li id='mainmenu-bulletin'><a href='bulletin.html'><span>Bulletin</span></a></li>"
			+"   <li id='mainmenu-calendar'><a href='calendar.html'><span>Calendar</span></a></li>"
			+"   <li id='mainmenu-resources'><a href='links.html'><span>Resources</span></a></li>"
			+"   <li id='mainmenu-gallery'><a href='fbalbums.html'><span>Gallery</span></a>"
			+"     <ul class=l1>"
			+"        <li><a href='#'><span>Pictures</span></a>"
			+"		      <ul class=l2>"
			+"		         <li><a href='fbalbums.html'><span>Facebook Albums</span></a></li>"
			+"		         <li><a href='gallery.html?option=galp4'><span>Pastor Rose Bender's Ordination</span></a></li>"
			+"		         <li><a href='gallery.html?option=galp3'><span>Joint Worship Service Vietnamese New Year 2012</span></a></li>"
			+"		         <li><a href='gallery.html?option=galp2'><span>Christmas 2009 Through the Eyes of a Child</span></a></li>"
			+"		         <li><a href='gallery.html?option=galp1'><span>Various Pictures</span></a></li>"
			+"		      </ul>"
			+"		 </li>"
			+"        <li><a href='#'><span>Videos</span></a>"
			+"		      <ul class=l2>"
			+"		         <li><a href='gallery.html?option=galv4'><span>VBS 2014</span></a></li>"
			+"		         <li><a href='gallery.html?option=galv3'><span>VBS 2013</span></a></li>"
			+"		         <li><a href='gallery.html?option=galv2'><span>VBS 2012</span></a></li>"
			+"		         <li><a href='gallery.html?option=galv1'><span>VBS 2011</span></a></li>"
			+"		      </ul>"
			+"	      </li>"
			+"        <li><a href='podcast.html'><span>Podcast</span></a></li>"
			+"      </ul>"
			+"  </li>"
			+"</ul>"
			+"</div>";
}